name: Clean up downloads

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "Set up SSH Agent"
        if: env.SSH_PRIVATE_KEY != null
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PRIVATE_KEY: ${{ secrets.DOWNLOADS_HOSTGATOR_DOT_MIXXX_DOT_ORG_KEY }}
          SSH_HOST: downloads-hostgator.mixxx.org
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${SSH_PRIVATE_KEY}"
          mkdir -p "${HOME}/.ssh"
          ssh-keyscan "${SSH_HOST}" >> "${HOME}/.ssh/known_hosts"
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "${GITHUB_ENV}"

      - name: Delete obsolete files
        if: env.SSH_AUTH_SOCK != null
        run: |
          mkdir empty_folder
          echo clang-tidy-ignore/ >> include_file.txt
          echo clang-tidy-ignore/* >> include_file.txt
          echo clang-tidy-warning/ >> include_file.txt
          echo clang-tidy-warning/* >> include_file.txt
          echo cmake-version-urls/ >> include_file.txt
          echo cmake-version-urls/* >> include_file.txt
          echo denormals_test_fix/ >> include_file.txt
          echo denormals_test_fix/* >> include_file.txt
          echo dependabot/ >> include_file.txt
          echo dependabot/* >> include_file.txt
          echo korg-kaoss-dj/ >> include_file.txt
          echo korg-kaoss-dj/* >> include_file.txt
          echo notarytool-2.4/ >> include_file.txt
          echo notarytool-2.4/* >> include_file.txt
          echo pr/ >> include_file.txt
          echo pr/* >> include_file.txt
          echo pr12370_winbuildenv_bat/ >> include_file.txt
          echo pr12370_winbuildenv_bat/* >> include_file.txt
          echo qt6/ >> include_file.txt
          echo qt6/* >> include_file.txt
          echo revert-12394-dependabot/ >> include_file.txt
          echo revert-12394-dependabot/* >> include_file.txt
          echo synclock-06-scratch-phase/ >> include_file.txt
          echo synclock-06-scratch-phase/* >> include_file.txt
          echo taglib_20_fail/ >> include_file.txt
          echo taglib_20_fail/* >> include_file.txt
          echo tracklists_shortkeys/ >> include_file.txt
          echo tracklists_shortkeys/* >> include_file.txt
          echo translate-spam-revert-2.4/ >> include_file.txt
          echo translate-spam-revert-2.4/* >> include_file.txt
          echo update-manifest/ >> include_file.txt
          echo update-manifest/* >> include_file.txt
          echo vcpkg_manifest/ >> include_file.txt
          echo vcpkg_manifest/* >> include_file.txt
          echo vcpkg_osx/ >> include_file.txt
          echo vcpkg_osx/* >> include_file.txt
          rsync --verbose --archive --times --recursive --delete --include-from=include_file.txt --exclude=* "empty_folder/" "${SSH_USER}@${SSH_HOST}:${DESTDIR}/"
        env:
          DESTDIR: public_html/downloads/snapshots
          SSH_HOST: downloads-hostgator.mixxx.org
          SSH_USER: mixxx
